[package]
name = "sir-optimizations"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sir-data.workspace = true

[dev-dependencies]
sir-parser.workspace = true
sir-test-utils = { path = "../../test-utils" }
