[package]
name = "sir-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sir"
path = "src/main.rs"

[dependencies]
sir-parser.workspace = true
sir-debug-backend.workspace = true
sir-optimizations.workspace = true
clap.workspace = true
