[package]
name = "sir-assembler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sir-data.workspace = true
thiserror.workspace = true
alloy-primitives.workspace = true
